### ISSUE TITLE
Crash While Playing Multiplayer

### ISSUE THREAD

**Issue by Pinkytwigosh** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#13]
Here's a pastebin of the crash. I thought it was because of the mods on the server but I was informed it was this mod.

https://pastebin.com/Buhu9463

**Comment by ApacheTech** [comment]
Hi, could you please give details as to what was happening when the crash occurred? This seems like it might be an edge-case issue, something that only crops up very rarely, so please give as much detail as you can.

I can see you're using 2.0.1; there is an updated version available here: https://mods.vintagestory.at/campaigncartographer.

While this won't fix the immediate error, it will help to eliminate any other issues that may have arisen.

**Comment by Pinkytwigosh** [comment]
I was eating a mushroom after I had made a campfire for light while playing
on the Vintage Civ server.

**Comment by ApacheTech** [comment]
Fixed in 2.1.0.
