### ISSUE TITLE
he asks to download 1 mod

### ISSUE THREAD

**Issue by ShadowMirok** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#28]
**Describe the Bug:**
When entering the single-player game mode, he asks to download 1 mod, if agrees, he crashes the game, if does not agree, he throws it into the server menu...

**To Reproduce:**
Create or Enter The World

**Expected Behaviour:**
He asks to download 1 mod, if agrees, he crashes the game, if does not agree, he throws it into the server menu

**Additional Context**
Some Users\Nexrem is specified in the crash

**Comment by ApacheTech** [comment]
Fixed within version 2.2.2.
