### ISSUE TITLE
[BUG] Mono crash when breaking a pit kiln

### ISSUE THREAD

**Issue by RogueRaiden** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#29]
**Describe the Bug:**
Very strange issue. I already opened a report on the main VS issue page when I didn't know what was happening. Some logs there.
https://github.com/anegostudios/VintageStory-Issues/issues/1860

Running a dedicated server on Ubuntu, with mono 6.12

When loaded with all of the mods server side, breaking an in progress pit kiln causes mono to crash. Removed Campaign Cartographer and kilns no longer crash when broken. Loading just Campaign Cartographer alone in the same world causes no crash.

I still need to find what mod is conflicting specifically.

**Comment by ApacheTech** [comment]
Hey. I'd need to see a stacktrace of the exception being thrown. Whatever text files you added to the other issue don't help. They correspond to raw memory addresses within your machine. I'd need your `client-main.txt`, `client-debug.txt`, `server-main.txt`, and `server-debug.txt` files.

I can't get HyperV working at the moment to be able to make a Linux VBox... and even then I'd be stumbling around in the dark without a clue what I'm doing. I haven't used Linux before, beyond messing around with Kali Linux. Hopefully, the actual game log files will hold the answer.

**Comment by ApacheTech** [comment]
Also, what are the specs of the server? Especially the number of Cores; and whether it's a shared VPS, or a dedicated Bare Bones box.
