### ISSUE TITLE
[BUG] 1.16 rc2 with pre2 version of campain cartographer : ui of Hcoverage and VCoverage values

### ISSUE THREAD

**Issue by Aledark789** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#6]
**Describe the Bug:**
add new waypoint type and try to use the up and down while holding mouse to increase/down crease value - doesnt work
if i do backspace it auto puts back 10 and if i backspace one and goes over 50..auto puts 50 back so erasing and reentering lets say 25 is harder than it should be

**Comment by ApacheTech** [comment]
Fixed in 2.0.0, by changing NumberInput elements to Sliders. Currently, `GuiElementNumberInput` elements are not working properly, and not safe enough to use for general input. There's no validation for input.
